"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci_sum(max):
    sum,a,b = 0,1,2
    while a <= max:
        if a % 2 == 0:
            sum += a
        a,b = b, a + b
    return str(sum)

print(fibonacci_sum(4000000))

#prints: 4613732



